name: Run Extractor

on:
  workflow_dispatch:
 
jobs:
  extract:
    runs-on: ubuntu-latest
    environment: dev # change this to match the dev environment created in settings 
    steps:
      - uses: actions/checkout@v2

      - name: Get Run ID
        id: get_run_id
        run: |
          echo "::set-output name=run_id::$(\
            gh run list \
              --workflow publish-extractor.yaml \
              --json conclusion,headSha,status,databaseId \
              --jq "[.[] | select( .conclusion == \"success\" ) | .databaseId][0]" \
          )"
         
          
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:          
          workflow: publish-extractor.yaml
          run_id: ${{steps.get_run_id.outputs.run_id}}
          name: extractor
          github_token: ${{secrets.GITHUB_TOKEN}}
          
      - name: Run extractor
        env:
          AZURE_CLIENT_ID: 0f79d8f3-8479-44e8-b432-f5781e65e01a #${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: 4wze8OURKjIIbL05bgjRalzr_VNgWN6s2H #${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          API_MANAGEMENT_SERVICE_NAME: ${{ secrets.API_MANAGEMENT_SERVICE_NAME }}
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: ${{ GITHUB.WORKSPACE }}/apimartifacts  # change this to the artifacts folder  
        run: |
          chmod +x ./extractor
          ./extractor
      - name: publish artifact
        uses: actions/upload-artifact@v2
        env:
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts  # change this to the artifacts folder  
        with:
          name: artifacts-from-portal
          path: ${{ GITHUB.WORKSPACE }}/${{ env.API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH }}    
          
  create-pull-request:
    needs: extract
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
          
      - name: Download artifacts-from-portal
        uses: actions/download-artifact@v2
        env:
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts  # change this to the artifacts folder  
        with:
          name: artifacts-from-portal
          path: "${{ GITHUB.WORKSPACE }}/${{ env.API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH }}"

      - name: Create artifacts pull request
        uses: peter-evans/create-pull-request@v3
        env:
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts  # change this to the artifacts folder          
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "updated extract from apim instance ${{ env.API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH }}"
          title: "${{ env.API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH }} - extract"
          body: >
            This PR is auto-generated by Github actions workflow
          labels: extract, automated pr      
